### ISSUE TITLE
Documentation? 

### ISSUE THREAD

**Issue by hopewise** [hyperfiction/HypPhoton#1]
Hello

Can you please tell us whats this project about? 

Also, us there any simple example to build native extension for windows that would call a function in dll and return result to haxe? ex: get hardware id

Thanks

**Comment by shoebox** [comment]
Hi 

This project is using the Photon SDK : https://www.exitgames.com/en/Realtime for realtime multiplayers game.

Take a look at that tutorial made by  Joshua : http://www.joshuagranick.com/blog/?p=734 ( it's old but work on windows ).
