### ISSUE TITLE
[Question] Why didn't you make iOS version too?

### ISSUE THREAD

**Issue by paala** [hyperfiction/HypPhoton#2]
Was there any OpenFL limitation that prevent you from making it?
Thanks

**Comment by shoebox** [comment]
Because I didn't needed it...

But you are more than welcome to do it and make a pull request.

**Comment by paala** [comment]
I was asking this because some user on Stencyl forums said that openFL on iOS can't use third party frameworks.
http://community.stencyl.com/index.php/topic,26007.msg187246.html#msg187246
Do you know about this limitation, is it true?
